In [3]:
import numpy as np


In [4]:
my_list = [1,3,5,7,9,11]

In [7]:
my_arr = np.array(my_list)

In [8]:
type(my_arr)

numpy.ndarray

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [12]:
arr = np.arange(0,25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
ranarr = np.random.randint(0,101, 25)

In [16]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1, 87, 29, 37,  1, 63, 59,
       20, 32, 75, 57, 21, 88, 48, 90])

In [17]:
ranarr.max()

99

In [18]:
ranarr.min() 

1

In [19]:
ranarr.argmax()

5

In [20]:
ranarr.argmin()

10

In [21]:
myarray = np.linspace(0, 10, 101)

In [22]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [23]:
arr = np.arange(0,11)

In [24]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr[0:6] = 120

In [26]:
arr

array([120, 120, 120, 120, 120, 120,   6,   7,   8,   9,  10])

In [27]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[0][0]

5

In [30]:
arr_2d[-1]

array([35, 40, 45])

In [31]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr = np.arange(1,11)

In [33]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
dice_rolls[dice_rolls > 2].size

    

19

In [37]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr = np.arange(0,11)

In [43]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr = np.arange(0,25).reshape((5,5))

In [48]:
arr


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
arr.sum()

300

In [50]:
arr.sum(axis=0)

array([50, 55, 60, 65, 70])

In [51]:
arr.sum(axis=1)

array([ 10,  35,  60,  85, 110])